---
title: "Anthropogenic change and biodiversity"
author: "Andrew J. Rominger"
date: "15 October 2018"
output: 
    ioslides_presentation:
        css: styles.css
        transition: 0
        incremental: true
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = FALSE)
```

```{css}
slide {
    background-position: center;
    background-repeat: no-repeat;
    background-size: contain;
}
```

```{r deps, include=FALSE}
# this ensures jquery is loaded
dep <- htmltools::htmlDependency(name = "jquery", version = "1.11.3", 
                                 src = system.file("rmd/h/jquery-1.11.3", package='rmarkdown'), 
                                 script = "jquery.min.js")
htmltools::attachDependencies(htmltools::tags$span(''), dep)
```

```{js move-id-background-color}
$(document).ready(function(){
    // for every article tag inside a slide tag
    $("slide > article").each(function(){
        // copy the article name to the parentNode's (the slide) ID
        this.parentNode.id=$(this).attr('name');
    });
});
```

```{r background-function,include=FALSE}
makeBG <- function(id, file)
{
    cat(
        sprintf('<style type="text/css">\n#%s {\nbackground-image: url(%s);\n}\n</style>',
                id, knitr::image_uri(file))
    )
}
```

## {.SlideClass #SlideID name=ThisSlide .flexbox .vcenter}
```{r results='asis',echo=FALSE}
makeBG(id='ThisSlide', 'biodiv.jpg')
```
<span style="font-size: 64px; color:#FFFFFF;">Biodiversity</span>



## Biodiversity

foo


## {.flexbox .vcenter}
<span style="font-size: 64px; color:#515151;">Thanks!</span>
<br/>
<br/>
Slides at [ajrominger.github.io/talks](ajrominger.github.io/talks)
